replicaCount: 1

image:
  repository: ghcr.io/skanderba8/k8s-gitops-platform/demo-api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  host: demo-api.local

env:
  APP_ENV: dev
  APP_VERSION: 1.0.0

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
