apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api-prod
  namespace: argocd
spec:
  project: gitops-platform
  source:
    repoURL: https://github.com/Skanderba8/k8s-gitops-platform.git
    targetRevision: HEAD
    path: charts/demo-api
    helm:
      parameters:
        - name: image.tag
          value: "latest"
        - name: replicaCount
          value: "2"
        - name: env.APP_ENV
          value: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true