apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api-dev
  namespace: argocd
spec:
  project: gitops-platform
  source:
    repoURL: https://github.com/Skanderba8/k8s-gitops-platform.git
    targetRevision: HEAD
    path: charts/demo-api
    helm:
      values: |
        replicaCount: 1
        env:
          APP_ENV: dev
        image:
          tag: "ae25fac830fa6903690e8f79a4cba133bac3cb7e"
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true