apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-platform
  namespace: argocd
spec:
  description: k8s-gitops-platform project
  sourceRepos:
    - https://github.com/Skanderba8/k8s-gitops-platform.git
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace